### PR TITLE
add Products page

### PR DESCRIPTION
**Pull request by hsnice16**
implemented products page.

Live: https://epic-golick-b54632.netlify.app/products.html

### CODE REVIEW

**Review by partha8 — APPROVED** [review]
Looks good, also this is my personal opinion but you can keep the sidebar to the left side (complete left), this way the user will always see the product cards and also you'll have more space to add more cards. I mean we always see this in all the e-commerce sites.

But everything looks good Himanshu! Great work

**Review by vrinda-mahajan — APPROVED** [review]
Looks good to me. Just a suggestion, make your filter section fixed.

**Comment by pradipgharge** [comment]
Looks good to me, just a little suggestion in the clothing cards, there is large white space between paragraph and pricing, looks a bit odd as compared cards above. Rest all good

**Review by Dev-AkshatGupta — APPROVED** [review]
LGTM UI looks great Himanshu : )

**Comment by hsnice16** [comment]
Thanks, everyone for reviewing this.

**Pull request merged**
