### PR TITLE
add Home page

### PR DESCRIPTION
**Pull request by hsnice16**
Implemented home page.

You can access the following pages
- Home
- Log In
- Sign Up
- Products
- Wish List
- Cart

Live: https://inclusive-mart-demo.netlify.app/

### CODE REVIEW

**Review by ApurvaSawant11 — APPROVED** [review]
Everything looks good. UI is also nice. Great work!

Just one thing. If all your components(like cards, buttons) have `border-radius: 0.2rem`, then I think the same radius should be given to your search bar. What do you think about this?

**Review by vishal804 — APPROVED** [review]

**Comment by vishal804** [comment]
Looks Good

**Comment by hsnice16** [comment]
> Everything looks good. UI is also nice. Great work!
> 
> Just one thing. If all your components(like cards, buttons) have `border-radius: 0.2rem`, then I think the same radius should be given to your search bar. What do you think about this?

I think it will look good. Thanks for pointing it.

image

**Comment by iamalhera** [comment]
UI looks nice, great work

**Comment by hsnice16** [comment]
Thank you for reviewing.

**Pull request merged**
